#!/usr/bin/env bash
#displays listening ports:
#That only shows listening sockets
#That shows the PID and name of the program to which each socket belongs
#t TCP
#n numeric
#p Port
#u UDP
netstat -tupln
