#!/usr/bin/env bash
#configures an Ubuntu server with the below requirements.
#Requirements:

#localhost resolves to 127.0.0.2
#facebook.com resolves to 8.8.8.8

sudo bash -c $"echo -e "127.0.0.2 localhost\n8.8.8.8 facebook.com" >> /etc/hosts"
