#!/usr/bin/env bash
#Write a Bash script that displays all active IPv4 IPs on the machine it s executed on.
#Example:

#10.0.2.15$
#127.0.0.1$
#Obviously, the IPs displayed may be different depending on which machine you are running the script on.
#Note that we can see our localhost IP :)

awk '{print $1}' /etc/hosts
